name: Master
on:
  push:
    branches:
      - main
  schedule:
    - cron: ' * */6 * * 1-5'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      run: |
        echo "Running!"