name: Master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      run: |
        python flipkart.py
